all:
	echo "hello desu, read this Makefile pls"

# install gitlab runner
install_gr_1:
	curl -L "https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.deb.sh" | sudo bash

install_gr_2:
	sudo apt-get install gitlab-runner

